
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-scripts
  namespace: {{ namespace }}
data:
  elasticsearch.sh: |-
    subscription-manager register --activationkey {{ subscriptionKey }} --org {{ subscriptionOrg }}
    subscription-manager attach --auto
    cat << EOF > /etc/yum.repos.d/elastic.repo
    [elasticsearch]
    name=Elasticsearch repository for 8.x packages
    baseurl=https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck=1
    gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled=0
    autorefresh=1
    type=rpm-md
    EOF
    update-crypto-policies --set DEFAULT:SHA1
    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dnf install -y --enablerepo=elasticsearch elasticsearch-8.7.0
    update-crypto-policies --set DEFAULT
    systemctl daemon-reload
    mkdir -p /srv/elasticsearch/config
    mkdir -p /srv/elasticsearch/data
    chown elasticsearch:elasticsearch /srv/elasticsearch -R
    mkfs.xfs /dev/disk/by-id/virtio-datadisk
    config=$(ls -1 /dev/disk/by-id/virtio-00yaml)
    mount $config /srv/elasticsearch/config
    mount /dev/disk/by-id/virtio-datadisk /srv/elasticsearch/data
    echo "$config /srv/elasticsearch/config iso9660 defaults 0 0" >> /etc/fstab
    echo '/dev/disk/by-id/virtio-datadisk /srv/elasticsearch/data   xfs defaults 0 0' >> /etc/fstab
    mv /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml.org
    mv /etc/elasticsearch/jvm.options       /etc/elasticsearch/jvm.options.org
    ln -sf /srv/elasticsearch/config/elasticsearch.conf /etc/elasticsearch/elasticsearch.yml
    ln -sf /srv/elasticsearch/config/jvm.options        /etc/elasticsearch/jvm.options
    systemctl enable elasticsearch --now
  system.sh: |-
    cert=$(ls -1 /dev/disk/by-id/virtio-00cert)
    mount $cert /etc/cockpit/ws-certs.d/
    if [ -f "/etc/cockpit/ws-certs.d/tls.crt" ]; then echo "$cert /etc/cockpit/ws-certs.d/ xfs defaults 0 0" >> /etc/fstab;
    else umount $cert; fi
    systemctl enable cockpit.socket --now
immutable: false
