apiVersion: v1
kind: Service
metadata:
  name: validated-pattern-svc
  namespace: validated-pattern
spec:
# ...
  selector:
    special: key 
  type: NodePort 
  ports: 
    - protocol: TCP
      port: 2222
      targetPort: 22
      nodePort: 30000