apiVersion: v1
kind: Service
metadata:
  name: ssh-vm
  namespace: validated-pattern
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 22
      protocol: TCP
  selector:
    special: key
  type: NodePort
