apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-vm
  namespace: your-namespace
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel-vm
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
        resources:
          requests:
            memory: 4Gi
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: rhel-pvc
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              runcmd:
                - subscription-manager register --username your-username --password your-password
                - subscription-manager attach --auto
                - subscription-manager repos --enable=rhel-7-server-rpms
                - yum -y update
                - yum -y install ansible
                - ansible-pull -U https://github.com/redhatryan/podman-ansible.git -i localhost, ansible-playbook/podman-setup.yaml
