apiVersion: v1
kind: Pod
metadata:
  name: ubi8
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"kibana"}]'
  labels:
    app: ubi8
    app.kubernetes.io/part-of: utility
    app.openshift.io/runtime: redhat
    app.openshift.io/name: utility
  namespace: REPLACE_ME
spec:
  volumes:
    - configMap:
        name: ubi8-install
      name: ubi8-install
    - secret:
        secretName: id-rsa
      name: id-rsa
  containers:
    - name: ubi8
      image: 'registry.access.redhat.com/ubi8/ubi'
      command: ["/bin/sh"]
      args: ["/usr/local/bin/install.sh"]
      stdin: true
      tty: true
      volumeMounts:
        - name: ubi8-install
          readOnly: true
          mountPath: /usr/local/bin/install.sh
          subPath: install.sh
        - name: id-rsa
          readOnly: true
          mountPath: /mnt/