bases:
  - ../../base

patchesStrategicMerge:
  - patches.yaml

secretGenerator:
  - name: github-runner-token
    literals:
      - RUNNER_TOKEN=your-real-runner-token
      - RUNNER_ORG=redhatryan/podman-actions
      #update this token!
      - RUNNER_LABELS=self-hosted,x64,podman