resources:
  - ../base

#patchesStrategicMerge:
#  - patches.yaml

secretGenerator:
  - name: github-runner-envs
    literals:
      - RUNNER_TOKEN=AYKPCABHCHZPWFMQQUEWUFLGSAJN6
      - RUNNER_ORG=redhatryan/podman-actions
      #update this token!
      - RUNNER_LABELS=self-hosted,x64,podman