apiVersion: v1
kind: ConfigMap
metadata:
  name: install-scripts
  namespace: validated-pattern
data:
  actions-runner-install.sh: |-
    subscription-manager register --activationkey rhel8-gha-virt-validated-pattern --org 11009103
    subscription-manager attach --auto
    sudo yum install libicu -y
    # Create a folder
    mkdir actions-runner && cd actions-runner
    # Download the latest runner package
    curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    # Extract the installer
    tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz
    # Create the runner and start the configuration experience
    export RUNNER_ALLOW_RUNASROOT=true
    sudo RUNNER_ALLOW_RUNASROOT=true ./config.sh --url https://github.com/redhatryan/podman-actions --token AYKPCAGDQGAFT2N3E5NLYC3GPSPLS --agent podman-actions --work podman-actions --runasservice
    # Last step, run it!
    sudo RUNNER_ALLOW_RUNASROOT=true ./run.sh
immutable: false
