kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  host: {{ name }}.{{ baseDomain }}
  to:
    kind: Service
    name: {{ name }}
  port:
    targetPort: cockpit
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None