resources:
  - ../base

patchesStrategicMerge:
  - patches.yaml

#secretGenerator:
#  - name: github-runner-envs
#    namespace: validated-pattern
#    literals:
#      - RUNNER_TOKEN=AYKPCADGOGS4SPYTUILKNGDGSA5GS
#      - RUNNER_VERSION=2.317.0
#      - RUNNER_ORG=redhatryan/podman-actions
#      #update this token!
#      - RUNNER_LABELS=self-hosted,x64,podman