---
- name: Set up rootless Podman for GitHub Actions with SELinux on localhost
  hosts: localhost
  become: yes
  connection: local
  vars:
    ansible_user: runner  # Set ansible_user to 'runner'

  tasks:
    - name: Create the 'runner' user
      user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create the home directory for the 'runner' user
      file:
        path: /home/{{ ansible_user }}
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Install dependencies for Podman
      package:
        name: 
          - podman
          - podman-docker
        state: present

    - name: Install SELinux dependencies
      package:
        name:
          - selinux-policy
          - selinux-policy-targeted
          - policycoreutils
          - policycoreutils-python-utils
        state: present

    - name: Ensure GitHub Actions self-hosted runner directory exists
      file:
        path: /home/{{ ansible_user }}/actions-runner
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      when: ansible_facts['filesystem']['/home/' + ansible_user + '/actions-runner'] is not defined

    - name: Download GitHub Actions self-hosted runner
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.308.0/actions-runner-linux-x64-2.308.0.tar.gz
        dest: /home/{{ ansible_user }}/actions-runner/actions-runner.tar.gz
        mode: '0755'

    - name: Extract GitHub Actions self-hosted runner
      unarchive:
        src: /home/{{ ansible_user }}/actions-runner/actions-runner.tar.gz
        dest: /home/{{ ansible_user }}/actions-runner
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Verify if svc.sh script exists
      stat:
        path: /home/{{ ansible_user }}/actions-runner/svc.sh
      register: svc_sh_status

    - name: Fail if svc.sh is missing
      fail:
        msg: "svc.sh script is missing in /home/{{ ansible_user }}/actions-runner"
      when: not svc_sh_status.stat.exists

    - name: Ensure svc.sh script is executable
      file:
        path: /home/{{ ansible_user }}/actions-runner/svc.sh
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: file
      when: svc_sh_status.stat.exists

    - name: Install GitHub Actions self-hosted runner
      shell: |
        ./svc.sh install {{ ansible_user }}
      args:
        chdir: /home/{{ ansible_user }}/actions-runner
      become_user: "{{ ansible_user }}"
      when: svc_sh_status.stat.exists

    - name: Enable rootless Podman
      shell: |
        loginctl enable-linger {{ ansible_user }}
      become_user: "{{ ansible_user }}"

    - name: Set up SELinux permissions for rootless Podman
      command: |
        sudo setsebool container_manage_cgroup 1
      args:
        warn: no

    - name: Configure SELinux for Podman and GitHub Actions runner
      command: |
        sudo semanage permissive -a container_t
      args:
        warn: no

    - name: Start GitHub Actions self-hosted runner service
      shell: |
        ./svc.sh start
      args:
        chdir: /home/{{ ansible_user }}/actions-runner
      become_user: "{{ ansible_user }}"
      when: svc_sh_status.stat.exists