name: Deploy Podman Hello to RHEL8 OCP-Virt VM
on:
  push:
jobs:
  rhel8-ovirt-deploy:
    name: Deploy Podman Hello to RHEL8 OCP-Virt VM
    runs-on: self-hosted
    steps:
      - name: Create container
        run: |
          su -runner -c "
          podman run quay.io/podman/hello
          "
      - name: Confirm successful deploy
        run: |
          echo "Podman Hello deployed successfully!"
